//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRMS.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qasja u ndryshua me sukses!.
        /// </summary>
        public static string AccessChangedSuccessfully {
            get {
                return ResourceManager.GetString("AccessChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qasja është e ndaluar!.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ju nuk jeni të autorizuar të qaseni në këtë faqe!.
        /// </summary>
        public static string AccessDeniedLong {
            get {
                return ResourceManager.GetString("AccessDeniedLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të dhënat e llogarisë.
        /// </summary>
        public static string AccountData {
            get {
                return ResourceManager.GetString("AccountData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llogaria është bllokuar.
        /// </summary>
        public static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metoda.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veprimet.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiv.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shto.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shto menynë.
        /// </summary>
        public static string AddMenu {
            get {
                return ResourceManager.GetString("AddMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shto nënmeny.
        /// </summary>
        public static string AddSubMenu {
            get {
                return ResourceManager.GetString("AddSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQ.
        /// </summary>
        public static string AL {
            get {
                return ResourceManager.GetString("AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shqip.
        /// </summary>
        public static string Albanian {
            get {
                return ResourceManager.GetString("Albanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatet e lejuara për foto.
        /// </summary>
        public static string AllowedFormatImage {
            get {
                return ResourceManager.GetString("AllowedFormatImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lejo njoftimet.
        /// </summary>
        public static string AllowNotification {
            get {
                return ResourceManager.GetString("AllowNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jeni të sigurt?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me llogari tjetër.
        /// </summary>
        public static string AsDiffUser {
            get {
                return ResourceManager.GetString("AsDiffUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizimi.
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizimet.
        /// </summary>
        public static string Authorizations {
            get {
                return ResourceManager.GetString("Authorizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizimet për menytë.
        /// </summary>
        public static string AuthorizationsForMenus {
            get {
                return ResourceManager.GetString("AuthorizationsForMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngarko.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulo.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndrysho grupin.
        /// </summary>
        public static string ChangeRole {
            get {
                return ResourceManager.GetString("ChangeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duhet të ketë të paktën {2} dhe maksimumi {1} karaktere..
        /// </summary>
        public static string CharacterLength {
            get {
                return ResourceManager.GetString("CharacterLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zgjedh.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim policy.
        /// </summary>
        public static string ClaimPolicy {
            get {
                return ResourceManager.GetString("ClaimPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbylle.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfirmo fjalëkalimin e ri!.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfirmo fjalëkalimin.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrolleri.
        /// </summary>
        public static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi aktual.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E errët.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të dhënat u fshinë me sukses!.
        /// </summary>
        public static string DataDeletedSuccessfully {
            get {
                return ResourceManager.GetString("DataDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të dhënat u regjistruan me sukses!.
        /// </summary>
        public static string DataRegisteredSuccessfully {
            get {
                return ResourceManager.GetString("DataRegisteredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të dhënat u ndryshuan me sukses!.
        /// </summary>
        public static string DataUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("DataUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fshij.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndrysho.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        public static string EN {
            get {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anglisht.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gabim.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ka ndodhur një gabim gjatë procesimit të të dhënave! Ju lutem provoni përsëri më vonë..
        /// </summary>
        public static string ErrorProcessingData {
            get {
                return ResourceManager.GetString("ErrorProcessingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femër.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keni harruar fjalëkalimin?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjinia.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ka çasje.
        /// </summary>
        public static string HasAccess {
            get {
                return ResourceManager.GetString("HasAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ka nënmeny.
        /// </summary>
        public static string HasSubMenu {
            get {
                return ResourceManager.GetString("HasSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikona.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shkruaj email-in për të dërguar linkun për të ndryshuar fjalëkalimin.
        /// </summary>
        public static string InputEmailToResetPassword {
            get {
                return ResourceManager.GetString("InputEmailToResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të dhënat nuk janë valide!.
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjuha.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbiemri.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E ndriçuar.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista e menyve.
        /// </summary>
        public static string ListMenus {
            get {
                return ResourceManager.GetString("ListMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista e nënmenyve.
        /// </summary>
        public static string ListSubMenus {
            get {
                return ResourceManager.GetString("ListSubMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyçu.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyçu - HRMS Riinvest.
        /// </summary>
        public static string LoginHRMS {
            get {
                return ResourceManager.GetString("LoginHRMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyçuni?.
        /// </summary>
        public static string LoginInstead {
            get {
                return ResourceManager.GetString("LoginInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyçuni për të filluar sesionin tuaj..
        /// </summary>
        public static string LoginToStart {
            get {
                return ResourceManager.GetString("LoginToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shkyçu.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mashkull.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madhësia maksimale e lejuar për foto.
        /// </summary>
        public static string MaxImageSize {
            get {
                return ResourceManager.GetString("MaxImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menyja.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri menysë.
        /// </summary>
        public static string MenuName {
            get {
                return ResourceManager.GetString("MenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menyja dhe nënmenyja.
        /// </summary>
        public static string MenuSubmenu {
            get {
                return ResourceManager.GetString("MenuSubmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri anglisht.
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri shqip.
        /// </summary>
        public static string NameSq {
            get {
                return ResourceManager.GetString("NameSq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi i ri.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jo.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Në rregull.
        /// </summary>
        public static string Okay {
            get {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hapur për.
        /// </summary>
        public static string OpenFor {
            get {
                return ResourceManager.GetString("OpenFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numri rendor.
        /// </summary>
        public static string OrdinalNumber {
            get {
                return ResourceManager.GetString("OrdinalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimet nuk përputhen!.
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të dhënat personale.
        /// </summary>
        public static string PersonalData {
            get {
                return ResourceManager.GetString("PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numri telefonit.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ju lutem prisni....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        public static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profili.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kjo fushë është obligative!.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rikthe.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rikthe fjalëkalimin.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupi.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruaj.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kërko.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dërgo email-in.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesioni ka mbaruar.
        /// </summary>
        public static string SessionTimedOut {
            get {
                return ResourceManager.GetString("SessionTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nënmenyja.
        /// </summary>
        public static string Submenu {
            get {
                return ResourceManager.GetString("Submenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri nënmenysë.
        /// </summary>
        public static string SubMenuName {
            get {
                return ResourceManager.GetString("SubMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sukses.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jeni të sigurt për fshirjen e kësaj menyje?.
        /// </summary>
        public static string SureYouWantToDeleteMenu {
            get {
                return ResourceManager.GetString("SureYouWantToDeleteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jeni të sigurt për fshirjen e kësaj nënmenyje?.
        /// </summary>
        public static string SureYouWantToDeleteSubMenu {
            get {
                return ResourceManager.GetString("SureYouWantToDeleteSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modaliteti aplikacionit.
        /// </summary>
        public static string TemplateMode {
            get {
                return ResourceManager.GetString("TemplateMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kjo llogari është bllokuar, ju lutem provoni përsëri më vonë..
        /// </summary>
        public static string ThisAccountLocked {
            get {
                return ResourceManager.GetString("ThisAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shkruaj fjalëkalimin për të rikthyer sesionin.
        /// </summary>
        public static string TypePasswordToSession {
            get {
                return ResourceManager.GetString("TypePasswordToSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E pamundur të ngarkohet përdoruesi..
        /// </summary>
        public static string UnableToLoadUser {
            get {
                return ResourceManager.GetString("UnableToLoadUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndryshoni të dhënat e llogarisë.
        /// </summary>
        public static string UpdateAccountData {
            get {
                return ResourceManager.GetString("UpdateAccountData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi juaj u ndryshua me sukses!.
        /// </summary>
        public static string UpdatedPassword {
            get {
                return ResourceManager.GetString("UpdatedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profili juaj u ndryshua me sukses!.
        /// </summary>
        public static string UpdatedProfile {
            get {
                return ResourceManager.GetString("UpdatedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndrysho foton.
        /// </summary>
        public static string UpdateImage {
            get {
                return ResourceManager.GetString("UpdateImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndryshoni fjalëkalimin.
        /// </summary>
        public static string UpdatePassword {
            get {
                return ResourceManager.GetString("UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndryshoni të dhënat personale.
        /// </summary>
        public static string UpdatePersonalData {
            get {
                return ResourceManager.GetString("UpdatePersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri përdoruesit.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kujdes.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
